

[package]
name = "optivaultai_cw721"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cosmwasm-std = "1.1"
cosmwasm-schema = "1.1"
cosmwasm-storage = "1.1"
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

cw-storage-plus = "0.16"
cw721 = "0.16"
cw721-base = { version = "0.16", features = ["library"] }
